### ISSUE TITLE
Can we have colourful JSON?

### ISSUE THREAD

**Issue by jacktuck** [jpwilliams/remit-cli#2]
<img src="https://media3.giphy.com/media/sIIhZliB2McAo/giphy.gif" width="350">

**Comment by jacktuck** [comment]
@jpwilliams thoughts on https://github.com/pinojs/pino

There is pretty param which will use chalk :)

**Comment by jacktuck** [comment]
Also lets us distinguish data / error

**Comment by jpwilliams** [comment]
I guess a nice feature would be to also set a `-r --raw` option which passes `JSON.stringify`'d data for use with PBCopy or other tools.

**Comment by jpwilliams** [comment]
Implemented in [Release v1.0.0](https://github.com/jpwilliams/remit-cli/releases/tag/1.0.0).
