### ISSUE TITLE
Pass in data with key-value pairs rather than JSON string

### ISSUE THREAD

**Issue by jacktuck** [jpwilliams/remit-cli#3]
## Instead of:
`remit-cli -u amqp://192.168.1.102 user.list.online  -d "{\"flat\": true, \"foo\": "\bar\"}"`

## We can do:
`remit-cli -u amqp://192.168.1.102 user.list.online  -d flat:true -d foo:bar`

**Comment by jpwilliams** [comment]
`-k --key`?

**Comment by jpwilliams** [comment]
If it's a separate property, what happens if I were to specify `-k` _and_ `-d`?

**Comment by jpwilliams** [comment]
Implemented in [Release v1.0.0](https://github.com/jpwilliams/remit-cli/releases/tag/1.0.0).
